version: '3.8'

services:
  web:
    build: .
    container_name: edukaz_web
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: edukaz_db
    restart: always
    environment:
      MYSQL_DATABASE: edukaz
      MYSQL_USER: edukaz_user
      MYSQL_PASSWORD: edukaz_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
